'use strict';
const TelegramBot = require('node-telegram-bot-api');
const { AppStore } = require('./appStore');
const currencyService = require('./currencyService');
const { setUserState, getUserState, clearUserState } = require('./stateStore');
const { sendTransferConfirm } = require('./profileService');
const RATES_RUB_PER_UNIT = Object.freeze({ USD: 30, RUB: 1, YER: 30 / 530, SAR: 30 / 3.7 });
for (const [code, rate] of Object.entries(RATES_RUB_PER_UNIT)) if (currencyService?.CURRENCIES?.[code]) currencyService.CURRENCIES[code].rubPerUnit = rate;
function normalizeCurrency(value) { const code=String(value||'RUB').trim().toUpperCase(); return RATES_RUB_PER_UNIT[code]?code:'RUB'; }
function userForChat(chatId){const store=global.__VAULTX_APP_STORE;return store&&chatId!=null?store.findUserById(chatId):null;}
function userCurrency(chatId){return normalizeCurrency(userForChat(chatId)?.currency||'RUB');}
function rubToDisplay(amountRub,currency){const code=normalizeCurrency(currency);const n=Number(amountRub);if(!Number.isFinite(n))return null;const value=n/RATES_RUB_PER_UNIT[code];const decimals=code==='YER'?0:2;return `${Number(value.toFixed(decimals)).toLocaleString('en-US',{maximumFractionDigits:decimals})} ${code}`;}
function convert(amount,sourceCurrency,targetCurrency){const n=Number(String(amount).replace(',','.'));const source=normalizeCurrency(sourceCurrency);if(!Number.isFinite(n))return null;return rubToDisplay(n*RATES_RUB_PER_UNIT[source],targetCurrency);}
const MONEY_WORDS=/(السعر|سعر|التكلفة|تكلفة|المبلغ|الرصيد|الإجمالي|اجمالي|الخصم|بعد الخصم|الحد الأدنى|الحد الاقصى|الحد الأقصى|سعر الوحدة|لكل\s*1000|price|cost|amount|balance|total|discount|minimum|maximum|unit\s*price|per\s*1000)/i;
const PRICE_CALLBACK=/(buy|purchase|number|virtual|sms|smm|game|topup|package|price|cost|order|service|offer|buynum)/i;
function replaceMoney(text,targetCurrency,context=''){let s=String(text??'');if(!s)return s;const target=normalizeCurrency(targetCurrency);s=s.replace(/â‚½/g,'RUB');const explicit=[{re:/₽\s*([0-9]+(?:[.,][0-9]+)?)/g,cur:'RUB'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*₽/g,cur:'RUB'},{re:/\bRUB\s*([0-9]+(?:[.,][0-9]+)?)/gi,cur:'RUB'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*RUB\b/gi,cur:'RUB'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*روبل/g,cur:'RUB'},{re:/\bUSD\s*([0-9]+(?:[.,][0-9]+)?)/gi,cur:'USD'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*USD\b/gi,cur:'USD'},{re:/\$\s*([0-9]+(?:[.,][0-9]+)?)/g,cur:'USD'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*\$/g,cur:'USD'},{re:/\bYER\s*([0-9]+(?:[.,][0-9]+)?)/gi,cur:'YER'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*YER\b/gi,cur:'YER'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*(?:ر\.ي|ريال\s*يمني)/g,cur:'YER'},{re:/\bSAR\s*([0-9]+(?:[.,][0-9]+)?)/gi,cur:'SAR'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*SAR\b/gi,cur:'SAR'},{re:/([0-9]+(?:[.,][0-9]+)?)\s*(?:ر\.س|ريال\s*سعودي)/g,cur:'SAR'}];for(const item of explicit)s=s.replace(item.re,(whole,raw)=>convert(raw,item.cur,target)||whole);s=s.replace(/(السعر|سعر|التكلفة|تكلفة|المبلغ|الرصيد|الإجمالي|اجمالي|الخصم|بعد الخصم|الحد الأدنى|الحد الاقصى|الحد الأقصى|سعر الوحدة|Price|Cost|Amount|Balance|Total|Discount|Minimum|Maximum|Unit\s*Price)(\s*[:：=|\-]?\s*)([0-9]+(?:[.,][0-9]+)?)/gi,(whole,label,sep,raw)=>`${label}${sep}${convert(raw,'RUB',target)||raw}`);if(PRICE_CALLBACK.test(String(context))||MONEY_WORDS.test(s))s=s.replace(/(^|[|•·]\s*)([0-9]+(?:[.,][0-9]+)?)\s*(?=$|[|•·])/g,(whole,prefix,raw)=>`${prefix}${convert(raw,'RUB',target)||raw}`);return s;}
function transformMarkup(markup,currency){if(!markup||typeof markup!=='object')return markup;if(Array.isArray(markup))return markup.map(x=>transformMarkup(x,currency));const out={...markup};const callback=String(out.callback_data||'');if(typeof out.text==='string')out.text=replaceMoney(out.text,currency,callback);for(const key of ['inline_keyboard','keyboard'])if(Array.isArray(out[key]))out[key]=out[key].map(row=>transformMarkup(row,currency));return out;}
function patchStore(){const original=AppStore.prototype.normalizeUser;if(original.__vaultxFinalCurrencyPatch)return;function patched(user){global.__VAULTX_APP_STORE=this;return original.call(this,user);}patched.__vaultxFinalCurrencyPatch=true;AppStore.prototype.normalizeUser=patched;}
function currencyKeyboard(lang,current){const names={USD:['🇺🇸','الدولار الأمريكي'],RUB:['🇷🇺','الروبل الروسي'],YER:['🇾🇪','الريال اليمني'],SAR:['🇸🇦','الريال السعودي']};return{inline_keyboard:[['USD','RUB'],['YER','SAR']].map(row=>row.map(code=>({text:`${code===current?'✅ ':''}${names[code][0]} ${names[code][1]}`,callback_data:`currency:set:${code}`}))).concat([[{text:lang==='ar'?'🔙 رجوع':'🔙 Back',callback_data:'menu:settings'}]])};}
function conversionKeyboard(lang){const labels={USD:'الدولار',RUB:'الروبل',YER:'الريال اليمني',SAR:'الريال السعودي'};const pairs=[['USD','RUB'],['USD','YER'],['USD','SAR'],['RUB','USD'],['RUB','YER'],['RUB','SAR'],['YER','USD'],['YER','RUB'],['YER','SAR'],['SAR','USD'],['SAR','RUB'],['SAR','YER']];return{inline_keyboard:pairs.map(([from,to])=>[{text:`💱 ${labels[from]} ← ${labels[to]}`,callback_data:`currency:convert:${from}:${to}`}]).concat([[{text:lang==='ar'?'🔙 رجوع':'🔙 Back',callback_data:'action:transfer_balance'}]])};}
function conversionText(lang){return lang==='ar'?'💱 <b>تحويل العملات</b>\n\nاختر العملة التي تريد التحويل منها وإليها.\n\nسيتم خصم المبلغ من رصيد العملة الأولى وإضافة الناتج إلى العملة الثانية.':'💱 <b>Currency Conversion</b>\n\nChoose the source and target currencies.\nThe source wallet will be debited and the converted amount added to the target wallet.';}
function conversionPrompt(lang,from,to){return lang==='ar'?`💱 تحويل <b>${from}</b> إلى <b>${to}</b>\n\nأرسل الآن المبلغ المراد تحويله.\nمثال: <code>5</code>\n\nأرسل Cancel للإلغاء.`:`💱 Convert <b>${from}</b> to <b>${to}</b>\n\nSend the amount to convert.\nExample: <code>5</code>\n\nSend Cancel to cancel.`;}
function patchTelegram(){
 const patch=(name,textIndex,optionsIndex,chatResolver)=>{const original=TelegramBot.prototype[name];if(typeof original!=='function'||original.__vaultxFinalCurrencyPatch)return;const wrapped=function(...args){const chatId=chatResolver?chatResolver(args):args[0];const currency=userCurrency(chatId);if(typeof args[textIndex]==='string')args[textIndex]=replaceMoney(args[textIndex],currency);const options=args[optionsIndex];if(options&&typeof options==='object'){if(typeof options.caption==='string')options.caption=replaceMoney(options.caption,currency);if(options.reply_markup)options.reply_markup=transformMarkup(options.reply_markup,currency);}return original.apply(this,args);};wrapped.__vaultxFinalCurrencyPatch=true;TelegramBot.prototype[name]=wrapped;};
 patch('sendMessage',1,2);patch('sendPhoto',1,2);patch('sendDocument',1,2);patch('sendVideo',1,2);patch('sendAudio',1,2);patch('editMessageText',0,1,args=>args[1]?.chat_id);patch('editMessageCaption',0,1,args=>args[1]?.chat_id);patch('editMessageReplyMarkup',0,1,args=>args[1]?.chat_id);
 const originalOn=TelegramBot.prototype.on;if(originalOn.__vaultxCurrencyRouterPatch)return;const wrappedOn=function(event,listener){
  if(event==='callback_query')return originalOn.call(this,event,async query=>{const store=global.__VAULTX_APP_STORE;const user=store?.findUserById(query?.from?.id);if(user&&typeof query.data==='string'){const lang=user.language||'ar';if(query.data==='menu:currency'){await this.sendMessage(query.message.chat.id,lang==='ar'?'💱 <b>اختر العملة التي تريد استخدامها للشراء والحساب</b>':'💱 <b>Select the currency used for purchases and your active wallet</b>',{parse_mode:'HTML',reply_markup:currencyKeyboard(lang,user.currency)});await this.answerCallbackQuery(query.id);query.data='noop';return listener(query);}if(query.data.startsWith('currency:set:')){const code=normalizeCurrency(query.data.split(':')[2]);store.setCurrency(user.userId,code);await this.answerCallbackQuery(query.id,{text:lang==='ar'?`تم اختيار ${code} كعملتك المختارة ✅`:`${code} selected ✅`});await this.sendMessage(query.message.chat.id,lang==='ar'?`✅ تم تغيير العملة المختارة إلى <b>${code}</b>.\nسيتم استخدام رصيد ${code} في المشتريات القادمة.`:`✅ Selected currency changed to <b>${code}</b>.\nFuture purchases use the ${code} wallet.`,{parse_mode:'HTML'});query.data='noop';return listener(query);}if(query.data==='transfer:currency'){await this.editMessageText(conversionText(lang),{chat_id:query.message.chat.id,message_id:query.message.message_id,parse_mode:'HTML',reply_markup:conversionKeyboard(lang)});await this.answerCallbackQuery(query.id);query.data='noop';return listener(query);}if(query.data.startsWith('currency:convert:')){const [, ,from,to]=query.data.split(':');setUserState(user.userId,'AWAITING_CURRENCY_CONVERSION',{fromCurrency:from,toCurrency:to});await this.editMessageText(conversionPrompt(lang,from,to),{chat_id:query.message.chat.id,message_id:query.message.message_id,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:lang==='ar'?'❌ إلغاء':'❌ Cancel',callback_data:'transfer:currency'}]]}});await this.answerCallbackQuery(query.id);query.data='noop';return listener(query);}}return listener(query);});
  if(event==='message')return originalOn.call(this,event,async msg=>{const store=global.__VAULTX_APP_STORE;const state=getUserState(msg?.from?.id);const user=store?.findUserById(msg?.from?.id);
   if(user&&state?.name==='AWAITING_CURRENCY_CONVERSION'){const lang=user.language||'ar';const raw=String(msg.text||'').trim();if(raw.toLowerCase()==='cancel'){clearUserState(user.userId);await this.sendMessage(msg.chat.id,lang==='ar'?'تم إلغاء تحويل العملات.':'Currency conversion canceled.');return;}const amount=Number(raw.replace(',','.'));const from=normalizeCurrency(state.fromCurrency);const to=normalizeCurrency(state.toCurrency);const available=store.getBalance(user.userId,from);if(!Number.isFinite(amount)||amount<=0){await this.sendMessage(msg.chat.id,lang==='ar'?'❌ أرسل مبلغاً صحيحاً.':'❌ Send a valid amount.');return;}if(available+1e-9<amount){await this.sendMessage(msg.chat.id,lang==='ar'?`❌ رصيدك في ${from} غير كافٍ. رصيدك: ${available}`:`❌ Insufficient ${from} balance. Your balance: ${available}`);return;}const converted=currencyService.convert(amount,from,to);const current=store.getBalance(user.userId,to);store.addBalanceInCurrency(user.userId,-amount,from);store.addBalanceInCurrency(user.userId,converted,to);store.addTransaction({type:'currency_conversion',userId:user.userId,amount,currency:from,targetCurrency:to,convertedAmount:converted,status:'completed'});clearUserState(user.userId);await this.sendMessage(msg.chat.id,lang==='ar'?`✅ تم التحويل بنجاح\n\n${amount} ${from} = <b>${Number(converted.toFixed(to==='YER'?0:2)).toLocaleString('en-US')} ${to}</b>\n\nرصيد ${to} الجديد: ${Number((current+converted).toFixed(6)).toLocaleString('en-US')} ${to}`:`✅ Conversion completed\n\n${amount} ${from} = <b>${converted.toLocaleString('en-US')} ${to}</b>\n\nNew ${to} balance: ${(current+converted).toLocaleString('en-US')} ${to}`,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:lang==='ar'?'💱 تحويل آخر':'💱 Convert Again',callback_data:'transfer:currency'}],[{text:lang==='ar'?'🏠 الرئيسية':'🏠 Main Menu',callback_data:'menu:main'}]]}});return;}
   if(user&&state?.name==='AWAITING_TRANSFER_PAYLOAD'){const lang=user.language||'ar';const text=String(msg.text||'').trim();if(text.toLowerCase()==='cancel'){clearUserState(user.userId);await this.sendMessage(msg.chat.id,lang==='ar'?'تم إلغاء عملية التحويل.':'Transfer canceled.');return;}const lines=text.split('\n').map(x=>x.trim()).filter(Boolean);if(lines.length!==2){await this.sendMessage(msg.chat.id,lang==='ar'?'أرسل سطرين: الآيدي ثم المبلغ بعملتك المختارة.':'Send two lines: receiver ID then amount in your selected currency.');return;}const receiver=store.findUserById(Number(lines[0]));const amountCurrency=Number(lines[1].replace(',','.'));if(!receiver){await this.sendMessage(msg.chat.id,lang==='ar'?'هذا الآيدي غير مسجل في البوت.':'This user ID is not registered.');return;}if(Number(receiver.userId)===Number(user.userId)){await this.sendMessage(msg.chat.id,lang==='ar'?'لا يمكنك التحويل إلى نفسك.':'You cannot transfer to yourself.');return;}if(!Number.isFinite(amountCurrency)||amountCurrency<=0){await this.sendMessage(msg.chat.id,lang==='ar'?'المبلغ غير صالح.':'Invalid amount.');return;}const available=store.getBalance(user.userId,user.currency);if(available+1e-9<amountCurrency){await this.sendMessage(msg.chat.id,lang==='ar'?`رصيدك غير كافٍ. رصيدك: ${available} ${user.currency}`:`Insufficient balance. Balance: ${available} ${user.currency}`);return;}const amountRub=currencyService.currencyToRub(amountCurrency,user.currency);setUserState(user.userId,'AWAITING_TRANSFER_CONFIRM',{targetUserId:receiver.userId,amount:amountRub,currency:user.currency,amountCurrency});await sendTransferConfirm(this,msg.chat.id,user,{senderName:user.firstName||user.username||'User',receiverName:receiver.firstName||receiver.username||'User',receiverId:receiver.userId,amountRub,currency:user.currency});return;}
   return listener(msg);});
  return originalOn.call(this,event,listener);
 };wrappedOn.__vaultxCurrencyRouterPatch=true;TelegramBot.prototype.on=wrappedOn;
}
patchStore();patchTelegram();
