const grizzlyServices = {
  whatsapp: "wa",
  telegram: "tg",
  facebook: "fb",
  instagram: "ig",
  twitter: "tw",
  google: "go",
  discord: "ds",
  viber: "vi",
  snapchat: "sn",
  tiktok: "tt",
  amazon: "am",
  apple: "ap",
  microsoft: "ms",
  linkedin: "li",
  uber: "ub",
  netflix: "nf",
  spotify: "sf",
  youtube: "yt",
};

const grizzlyCountries = {
  "0": { name_ar: "روسيا", flag: "🇷🇺" },
  "1": { name_ar: "أوكرانيا", flag: "🇺🇦" },
  "2": { name_ar: "كازاخستان", flag: "🇰🇿" },
  "3": { name_ar: "الصين", flag: "🇨🇳" },
  "4": { name_ar: "الفلبين", flag: "🇵🇭" },
  "5": { name_ar: "ميانمار", flag: "🇲🇲" },
  "6": { name_ar: "إندونيسيا", flag: "🇮🇩" },
  "7": { name_ar: "ماليزيا", flag: "🇲🇾" },
  "8": { name_ar: "كينيا", flag: "🇰🇪" },
  "9": { name_ar: "تنزانيا", flag: "🇹🇿" },
  "10": { name_ar: "فيتنام", flag: "🇻🇳" },
  "11": { name_ar: "قيرغيزستان", flag: "🇰🇬" },
  "12": { name_ar: "أمريكا (افتراضي)", flag: "🇺🇸" },
  "13": { name_ar: "إسرائيل", flag: "🇮🇱" },
  "14": { name_ar: "هونغ كونغ", flag: "🇭🇰" },
  "15": { name_ar: "بولندا", flag: "🇵🇱" },
  "16": { name_ar: "بريطانيا", flag: "🇬🇧" },
  "17": { name_ar: "مدغشقر", flag: "🇲🇬" },
  "18": { name_ar: "الكونغو", flag: "🇨🇬" },
  "19": { name_ar: "نيجيريا", flag: "🇳🇬" },
  "20": { name_ar: "ماكاو", flag: "🇲🇴" },
  "21": { name_ar: "مصر", flag: "🇪🇬" },
  "22": { name_ar: "الهند", flag: "🇮🇳" },
  "23": { name_ar: "أيرلندا", flag: "🇮🇪" },
  "24": { name_ar: "كمبوديا", flag: "🇰🇭" },
  "25": { name_ar: "لاوس", flag: "🇱🇦" },
  "26": { name_ar: "هايتي", flag: "🇭🇹" },
  "27": { name_ar: "ساحل العاج", flag: "🇨🇮" },
  "28": { name_ar: "غامبيا", flag: "🇬🇲" },
  "29": { name_ar: "صربيا", flag: "🇷🇸" },
  "30": { name_ar: "اليمن", flag: "🇾🇪" },
  "31": { name_ar: "جنوب أفريقيا", flag: "🇿🇦" },
  "32": { name_ar: "رومانيا", flag: "🇷🇴" },
  "33": { name_ar: "كولومبيا", flag: "🇨🇴" },
  "34": { name_ar: "إستونيا", flag: "🇪🇪" },
  "35": { name_ar: "أذربيجان", flag: "🇦🇿" },
  "36": { name_ar: "كندا", flag: "🇨🇦" },
  "37": { name_ar: "المغرب", flag: "🇲🇦" },
  "38": { name_ar: "غانا", flag: "🇬🇭" },
  "39": { name_ar: "الأرجنتين", flag: "🇦🇷" },
  "40": { name_ar: "أوزبكستان", flag: "🇺🇿" },
  "41": { name_ar: "الكاميرون", flag: "🇨🇲" },
  "42": { name_ar: "تشاد", flag: "🇹🇩" },
  "43": { name_ar: "ألمانيا", flag: "🇩🇪" },
  "44": { name_ar: "ليتوانيا", flag: "🇱🇹" },
  "45": { name_ar: "كرواتيا", flag: "🇭🇷" },
  "46": { name_ar: "السويد", flag: "🇸🇪" },
  "47": { name_ar: "العراق", flag: "🇮🇶" },
  "48": { name_ar: "هولندا", flag: "🇳🇱" },
  "49": { name_ar: "لاتفيا", flag: "🇱🇻" },
  "50": { name_ar: "النمسا", flag: "🇦🇹" },
  "51": { name_ar: "بيلاروسيا", flag: "🇧🇾" },
  "52": { name_ar: "تايلاند", flag: "🇹🇭" },
  "53": { name_ar: "السعودية", flag: "🇸🇦" },
  "54": { name_ar: "المكسيك", flag: "🇲🇽" },
  "55": { name_ar: "تايوان", flag: "🇹🇼" },
  "56": { name_ar: "إسبانيا", flag: "🇪🇸" },
  "57": { name_ar: "إيران", flag: "🇮🇷" },
  "58": { name_ar: "الجزائر", flag: "🇩🇿" },
  "60": { name_ar: "بنغلاديش", flag: "🇧🇩" },
  "61": { name_ar: "السنغال", flag: "🇸🇳" },
  "62": { name_ar: "تركيا", flag: "🇹🇷" },
  "63": { name_ar: "جمهورية التشيك", flag: "🇨🇿" },
  "64": { name_ar: "سريلانكا", flag: "🇱🇰" },
  "65": { name_ar: "بيرو", flag: "🇵🇪" },
  "66": { name_ar: "باكستان", flag: "🇵🇰" },
  "67": { name_ar: "نيوزيلندا", flag: "🇳🇿" },
  "68": { name_ar: "غينيا", flag: "🇬🇳" },
  "69": { name_ar: "مالي", flag: "🇲🇱" },
  "70": { name_ar: "فنزويلا", flag: "🇻🇪" },
  "71": { name_ar: "إثيوبيا", flag: "🇪🇹" },
  "72": { name_ar: "منغوليا", flag: "🇲🇳" },
  "73": { name_ar: "البرازيل", flag: "🇧🇷" },
  "74": { name_ar: "أفغانستان", flag: "🇦🇫" },
  "75": { name_ar: "أوغندا", flag: "🇺🇬" },
  "76": { name_ar: "أنغولا", flag: "🇦🇴" },
  "77": { name_ar: "قبرص", flag: "🇨🇾" },
  "78": { name_ar: "فرنسا", flag: "🇫🇷" },
  "79": { name_ar: "بابوا غينيا الجديدة", flag: "🇵🇬" },
  "80": { name_ar: "موزمبيق", flag: "🇲🇿" },
  "81": { name_ar: "نيبال", flag: "🇳🇵" },
  "82": { name_ar: "بلجيكا", flag: "🇧🇪" },
  "83": { name_ar: "بلغاريا", flag: "🇧🇬" },
  "84": { name_ar: "المجر", flag: "🇭🇺" },
  "85": { name_ar: "مولدوفا", flag: "🇲🇩" },
  "86": { name_ar: "إيطاليا", flag: "🇮🇹" },
  "87": { name_ar: "باراغواي", flag: "🇵🇾" },
  "88": { name_ar: "هندوراس", flag: "🇭🇳" },
  "89": { name_ar: "تونس", flag: "🇹🇳" },
  "90": { name_ar: "نيكاراغوا", flag: "🇳🇮" },
  "92": { name_ar: "بوليفيا", flag: "🇧🇴" },
  "94": { name_ar: "غواتيمالا", flag: "🇬🇹" },
  "95": { name_ar: "الإمارات", flag: "🇦🇪" },
  "96": { name_ar: "زيمبابوي", flag: "🇿🇼" },
  "98": { name_ar: "السودان", flag: "🇸🇩" },
  "109": { name_ar: "جمهورية الدومينيكان", flag: "🇩🇴" },
  "114": { name_ar: "بورتوريكو", flag: "🇵🇷" },
  "117": { name_ar: "البرتغال", flag: "🇵🇹" },
  "126": { name_ar: "أوروغواي", flag: "🇺🇾" },
  "135": { name_ar: "النيجر", flag: "🇳🇪" },
  "146": { name_ar: "الكويت", flag: "🇰🇼" },
  "150": { name_ar: "رواندا", flag: "🇷🇼" },
  "152": { name_ar: "بوركينا فاسو", flag: "🇧🇫" },
  "153": { name_ar: "لبنان", flag: "🇱🇧" },
  "158": { name_ar: "بوروندي", flag: "🇧🇮" },
  "161": { name_ar: "عمان", flag: "🇴🇲" },
  "163": { name_ar: "قطر", flag: "🇶🇦" },
  "171": { name_ar: "البوسنة والهرسك", flag: "🇧🇦" },
  "174": { name_ar: "الأردن", flag: "🇯🇴" },
  "187": { name_ar: "أمريكا/الولايات", flag: "🇺🇸" },
};

const GRIZZLY_COUNTRY_FALLBACK = { name_ar: "دولة أخرى", flag: "🌍" };

const grizzlyAppAliases = {
  "twitter/x": "twitter",
  x: "twitter",
  gmail: "google",
  "واتساب": "whatsapp",
  "واتس اب": "whatsapp",
  "تيليجرام": "telegram",
  "فيسبوك": "facebook",
  "إنستجرام": "instagram",
  "تويتر/x": "twitter",
  "تويتر": "twitter",
  "سناب شات": "snapchat",
  "سناب": "snapchat",
  "ديسكورد": "discord",
  "فايبر": "viber",
  "لاين": "line",
  "وي شات": "google",
  "جيميل": "google",
  "تيك توك": "tiktok",
  "أمازون": "amazon",
  "آبل": "apple",
  "ابل": "apple",
  "مايكروسوفت": "microsoft",
  "لينكدإن": "linkedin",
  "لينكد ان": "linkedin",
  "أوبر": "uber",
  "كريم": "uber",
  "نتفليكس": "netflix",
  "سبوتيفاي": "spotify",
  "يوتيوب": "youtube",
};

function normalizeGrizzlyAppName(appName) {
  return String(appName || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

function getGrizzlyServiceCode(appName) {
  const normalized = normalizeGrizzlyAppName(appName);
  const aliased = grizzlyAppAliases[normalized] || normalized;
  return grizzlyServices[aliased] || null;
}

function getGrizzlyCountryMeta(countryId) {
  return grizzlyCountries[String(countryId)] || GRIZZLY_COUNTRY_FALLBACK;
}

module.exports = {
  grizzlyServices,
  grizzlyCountries,
  GRIZZLY_COUNTRY_FALLBACK,
  getGrizzlyServiceCode,
  getGrizzlyCountryMeta,
};
